[versions]
kotlin = "2.4.0"

chasm = "2.0.0-SNAPSHOT"
weh = "0.7.0-SNAPSHOT"

[libraries]
chasm = { group = "io.github.charlietap.chasm", name = "chasm", version.ref = "chasm" }
weh-chasm-emscripten = { group = "at.released.weh", name = "bindings-chasm-emscripten", version.ref = "weh" }
weh-chasm-wasip1 = { group = "at.released.weh", name = "bindings-chasm-wasip1", version.ref = "weh" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
